name: cgal-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python <=3.12
  - pip
  - cmake
  - compas
  - compas_viewer
  - pip:
      - -r requirements-dev.txt
      - -r requirements-docs.txt
      - .
